In [5]:
# pip install numpy
# conda install numpy
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros(5) # 1solo numros para el arreglos
np.zeros([5,5]) #1 lista o tupla para una matriz de n dimenciones
np.zeros((5,5))
np.zeros([1,2,2,2,2])
np.zeros([1000,200])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.eye(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(4,20) #[4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(-12,1) #[-21,1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [20]:
np.arange(0,20,2) # Del [0,20[ en intervalos de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(0,2.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.zeros(20).reshape(2,5,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [27]:
len(np.ones(12))#longitud del arreglo

12

In [29]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
len(np.ones(12).reshape(4,3))


4

In [32]:
np.ones(12).reshape(4,3).shape #numero de dimenciones

(4, 3)

In [37]:
arreglo =np.arange(12).reshape(4,3)
print (arreglo)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
arreglo[2][1]

7

In [39]:
np.arange(12).reshape(4,3)[2][1]

7

In [40]:
a= np.array([10,10,10])
b= np.array([5,5,5])

In [41]:
#Suma
a+b

array([15, 15, 15])

In [42]:
#Resta
a-b

array([5, 5, 5])

In [43]:
#Suma
a+7

array([17, 17, 17])

In [46]:
a*b

array([50, 50, 50])

In [47]:
a*3

array([30, 30, 30])

In [51]:
#division /
a / 2

array([5., 5., 5.])

In [50]:
#modulo
a % b

array([0, 0, 0], dtype=int32)

In [6]:
muestra= np.arange(20).reshape(5,2,2)

In [79]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [93]:
#filtrar para obtener mayores que 5 menores 14 y pares
respuesta_glucosa=muestra>5
muestraFilt1=muestra[respuesta_glucosa]
respuesta_glucosa1=muestraFilt1<14
muestraFilt2=muestraFilt1[respuesta_glucosa1]
respuesta_glucosa2=muestraFilt2 % 2==0
muestraFilt2[respuesta_glucosa2]

array([ 6,  8, 10, 12])

In [88]:
respuesta_glucosa2

array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [82]:
muestra[respuesta_glucosa1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
muestra[(muestra>5)&(muestra<14)&(muestra%2==0)]

array([ 6,  8, 10, 12])

In [15]:
A=np.arange(4).reshape(2,2)
B=np.arange(4).reshape(2,2)

In [12]:
arreglo_doce=np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arreglo_doce.sum()

66

In [13]:
arreglo_doce.max()

11

In [ ]:
arreglo_doce[5:].sum()

In [16]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [17]:
arreglo_doce.reshape(3,2,2).sum()

66

In [18]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [19]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [20]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])