In [2]:
import numpy as np

In [3]:
arreglo_grados=np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes=arreglo_grados*np.pi/180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [25]:
numero_random=np.random.randint(
    11
)
numero_random

8

In [26]:
numero_random_negativo=np.random.randint(
    -9,
    2
)
numero_random_negativo

-1

In [10]:
arreglo_random =np.random.randint(
    10,
    20,
    8
)
arreglo_random

array([14, 12, 12, 15, 13, 14, 11, 11])

In [11]:
np.random.rand(9)

array([0.87075178, 0.39768931, 0.84455963, 0.77707757, 0.02677368,
       0.32303977, 0.59301406, 0.14945552, 0.87021855])

In [12]:
np.random.rand(3,2)


array([[0.0140762 , 0.31935147],
       [0.53571945, 0.67161515],
       [0.2943938 , 0.58772831]])

In [13]:
np.average(arreglo_random)

12.75

In [24]:
np.mean(arreglo_random)

12.75

In [15]:
np.median(arreglo_random)

12.5

In [23]:
np.std(arreglo_random)

1.3919410907075054

In [22]:
np.var(arreglo_random)

1.9375

In [20]:
arreglo_random.mean()

12.75